package com.blackhawk.servicenow.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-02-10T12:16:54.949-05:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://www.service-now.com", name = "ServiceNowSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceNowSoap {

    @RequestWrapper(localName = "insert", targetNamespace = "http://www.service-now.com/sys_user", className = "com.blackhawk.servicenow.soap.client.Insert")
    @WebMethod(action = "http://www.service-now.com/sys_user/insert")
    @ResponseWrapper(localName = "insertResponse", targetNamespace = "http://www.service-now.com/sys_user", className = "com.blackhawk.servicenow.soap.client.InsertResponse")
    public void insert(
        @WebParam(name = "accumulated_roles", targetNamespace = "")
        java.lang.String accumulatedRoles,
        @WebParam(name = "active", targetNamespace = "")
        java.lang.Boolean active,
        @WebParam(name = "auditor", targetNamespace = "")
        java.lang.Boolean auditor,
        @WebParam(name = "building", targetNamespace = "")
        java.lang.String building,
        @WebParam(name = "calendar_integration", targetNamespace = "")
        java.lang.String calendarIntegration,
        @WebParam(name = "city", targetNamespace = "")
        java.lang.String city,
        @WebParam(name = "company", targetNamespace = "")
        java.lang.String company,
        @WebParam(name = "cost_center", targetNamespace = "")
        java.lang.String costCenter,
        @WebParam(name = "country", targetNamespace = "")
        java.lang.String country,
        @WebParam(name = "date_format", targetNamespace = "")
        java.lang.String dateFormat,
        @WebParam(name = "date_time_format", targetNamespace = "")
        java.lang.String dateTimeFormat,
        @WebParam(name = "default_perspective", targetNamespace = "")
        java.lang.String defaultPerspective,
        @WebParam(name = "department", targetNamespace = "")
        java.lang.String department,
        @WebParam(name = "edu_status", targetNamespace = "")
        java.lang.String eduStatus,
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email,
        @WebParam(name = "employee_number", targetNamespace = "")
        java.lang.String employeeNumber,
        @WebParam(name = "failed_attempts", targetNamespace = "")
        java.math.BigInteger failedAttempts,
        @WebParam(name = "first_name", targetNamespace = "")
        java.lang.String firstName,
        @WebParam(name = "gender", targetNamespace = "")
        java.lang.String gender,
        @WebParam(name = "home_phone", targetNamespace = "")
        java.lang.String homePhone,
        @WebParam(name = "introduction", targetNamespace = "")
        java.lang.String introduction,
        @WebParam(name = "last_login", targetNamespace = "")
        java.lang.String lastLogin,
        @WebParam(name = "last_login_device", targetNamespace = "")
        java.lang.String lastLoginDevice,
        @WebParam(name = "last_login_time", targetNamespace = "")
        java.lang.String lastLoginTime,
        @WebParam(name = "last_name", targetNamespace = "")
        java.lang.String lastName,
        @WebParam(name = "last_password", targetNamespace = "")
        java.lang.String lastPassword,
        @WebParam(name = "ldap_server", targetNamespace = "")
        java.lang.String ldapServer,
        @WebParam(name = "location", targetNamespace = "")
        java.lang.String location,
        @WebParam(name = "locked_out", targetNamespace = "")
        java.lang.Boolean lockedOut,
        @WebParam(name = "manager", targetNamespace = "")
        java.lang.String manager,
        @WebParam(name = "middle_name", targetNamespace = "")
        java.lang.String middleName,
        @WebParam(name = "mobile_phone", targetNamespace = "")
        java.lang.String mobilePhone,
        @WebParam(mode = WebParam.Mode.INOUT, name = "name", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> name,
        @WebParam(name = "notification", targetNamespace = "")
        java.math.BigInteger notification,
        @WebParam(name = "password_needs_reset", targetNamespace = "")
        java.lang.Boolean passwordNeedsReset,
        @WebParam(name = "phone", targetNamespace = "")
        java.lang.String phone,
        @WebParam(name = "photo", targetNamespace = "")
        java.lang.String photo,
        @WebParam(name = "preferred_language", targetNamespace = "")
        java.lang.String preferredLanguage,
        @WebParam(name = "roles", targetNamespace = "")
        java.lang.String roles,
        @WebParam(name = "sales_account", targetNamespace = "")
        java.lang.String salesAccount,
        @WebParam(name = "sales_contact", targetNamespace = "")
        java.lang.String salesContact,
        @WebParam(name = "schedule", targetNamespace = "")
        java.lang.String schedule,
        @WebParam(name = "source", targetNamespace = "")
        java.lang.String source,
        @WebParam(name = "state", targetNamespace = "")
        java.lang.String state,
        @WebParam(name = "street", targetNamespace = "")
        java.lang.String street,
        @WebParam(name = "time_format", targetNamespace = "")
        java.lang.String timeFormat,
        @WebParam(name = "time_zone", targetNamespace = "")
        java.lang.String timeZone,
        @WebParam(name = "title", targetNamespace = "")
        java.lang.String title,
        @WebParam(name = "u_active_in_incident_tracking", targetNamespace = "")
        java.lang.Boolean uActiveInIncidentTracking,
        @WebParam(name = "u_active_in_partners_list", targetNamespace = "")
        java.lang.Boolean uActiveInPartnersList,
        @WebParam(name = "u_cube_number", targetNamespace = "")
        java.lang.String uCubeNumber,
        @WebParam(name = "u_director", targetNamespace = "")
        java.lang.String uDirector,
        @WebParam(name = "u_employee_type", targetNamespace = "")
        java.lang.String uEmployeeType,
        @WebParam(name = "u_group", targetNamespace = "")
        java.lang.String uGroup,
        @WebParam(name = "u_licensed_user", targetNamespace = "")
        java.lang.String uLicensedUser,
        @WebParam(name = "u_merchant_onboarding", targetNamespace = "")
        java.lang.String uMerchantOnboarding,
        @WebParam(name = "u_outage_notification", targetNamespace = "")
        java.lang.Boolean uOutageNotification,
        @WebParam(name = "u_page_at", targetNamespace = "")
        java.lang.String uPageAt,
        @WebParam(name = "u_partner_name", targetNamespace = "")
        java.lang.String uPartnerName,
        @WebParam(name = "u_preferred_name", targetNamespace = "")
        java.lang.String uPreferredName,
        @WebParam(name = "u_safeway_id", targetNamespace = "")
        java.lang.String uSafewayId,
        @WebParam(name = "u_type_of_user", targetNamespace = "")
        java.lang.String uTypeOfUser,
        @WebParam(name = "u_vp", targetNamespace = "")
        java.lang.String uVp,
        @WebParam(name = "user_name", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "user_password", targetNamespace = "")
        java.lang.String userPassword,
        @WebParam(name = "vip", targetNamespace = "")
        java.lang.Boolean vip,
        @WebParam(name = "zip", targetNamespace = "")
        java.lang.String zip,
        @WebParam(mode = WebParam.Mode.OUT, name = "sys_id", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> sysId
    );

    @WebResult(name = "count", targetNamespace = "")
    @RequestWrapper(localName = "deleteRecord", targetNamespace = "http://www.service-now.com/sys_user", className = "com.blackhawk.servicenow.soap.client.DeleteRecord")
    @WebMethod(action = "http://www.service-now.com/sys_user/deleteRecord")
    @ResponseWrapper(localName = "deleteRecordResponse", targetNamespace = "http://www.service-now.com/sys_user", className = "com.blackhawk.servicenow.soap.client.DeleteRecordResponse")
    public java.lang.String deleteRecord(
        @WebParam(name = "sys_id", targetNamespace = "")
        java.lang.String sysId
    );

    @RequestWrapper(localName = "update", targetNamespace = "http://www.service-now.com/sys_user", className = "com.blackhawk.servicenow.soap.client.Update")
    @WebMethod(action = "http://www.service-now.com/sys_user/update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://www.service-now.com/sys_user", className = "com.blackhawk.servicenow.soap.client.UpdateResponse")
    public void update(
        @WebParam(name = "accumulated_roles", targetNamespace = "")
        java.lang.String accumulatedRoles,
        @WebParam(name = "active", targetNamespace = "")
        java.lang.Boolean active,
        @WebParam(name = "auditor", targetNamespace = "")
        java.lang.Boolean auditor,
        @WebParam(name = "building", targetNamespace = "")
        java.lang.String building,
        @WebParam(name = "calendar_integration", targetNamespace = "")
        java.lang.String calendarIntegration,
        @WebParam(name = "city", targetNamespace = "")
        java.lang.String city,
        @WebParam(name = "company", targetNamespace = "")
        java.lang.String company,
        @WebParam(name = "cost_center", targetNamespace = "")
        java.lang.String costCenter,
        @WebParam(name = "country", targetNamespace = "")
        java.lang.String country,
        @WebParam(name = "date_format", targetNamespace = "")
        java.lang.String dateFormat,
        @WebParam(name = "date_time_format", targetNamespace = "")
        java.lang.String dateTimeFormat,
        @WebParam(name = "default_perspective", targetNamespace = "")
        java.lang.String defaultPerspective,
        @WebParam(name = "department", targetNamespace = "")
        java.lang.String department,
        @WebParam(name = "edu_status", targetNamespace = "")
        java.lang.String eduStatus,
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email,
        @WebParam(name = "employee_number", targetNamespace = "")
        java.lang.String employeeNumber,
        @WebParam(name = "failed_attempts", targetNamespace = "")
        java.math.BigInteger failedAttempts,
        @WebParam(name = "first_name", targetNamespace = "")
        java.lang.String firstName,
        @WebParam(name = "gender", targetNamespace = "")
        java.lang.String gender,
        @WebParam(name = "home_phone", targetNamespace = "")
        java.lang.String homePhone,
        @WebParam(name = "introduction", targetNamespace = "")
        java.lang.String introduction,
        @WebParam(name = "last_login", targetNamespace = "")
        java.lang.String lastLogin,
        @WebParam(name = "last_login_device", targetNamespace = "")
        java.lang.String lastLoginDevice,
        @WebParam(name = "last_login_time", targetNamespace = "")
        java.lang.String lastLoginTime,
        @WebParam(name = "last_name", targetNamespace = "")
        java.lang.String lastName,
        @WebParam(name = "last_password", targetNamespace = "")
        java.lang.String lastPassword,
        @WebParam(name = "ldap_server", targetNamespace = "")
        java.lang.String ldapServer,
        @WebParam(name = "location", targetNamespace = "")
        java.lang.String location,
        @WebParam(name = "locked_out", targetNamespace = "")
        java.lang.Boolean lockedOut,
        @WebParam(name = "manager", targetNamespace = "")
        java.lang.String manager,
        @WebParam(name = "middle_name", targetNamespace = "")
        java.lang.String middleName,
        @WebParam(name = "mobile_phone", targetNamespace = "")
        java.lang.String mobilePhone,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "notification", targetNamespace = "")
        java.math.BigInteger notification,
        @WebParam(name = "password_needs_reset", targetNamespace = "")
        java.lang.Boolean passwordNeedsReset,
        @WebParam(name = "phone", targetNamespace = "")
        java.lang.String phone,
        @WebParam(name = "photo", targetNamespace = "")
        java.lang.String photo,
        @WebParam(name = "preferred_language", targetNamespace = "")
        java.lang.String preferredLanguage,
        @WebParam(name = "roles", targetNamespace = "")
        java.lang.String roles,
        @WebParam(name = "sales_account", targetNamespace = "")
        java.lang.String salesAccount,
        @WebParam(name = "sales_contact", targetNamespace = "")
        java.lang.String salesContact,
        @WebParam(name = "schedule", targetNamespace = "")
        java.lang.String schedule,
        @WebParam(name = "source", targetNamespace = "")
        java.lang.String source,
        @WebParam(name = "state", targetNamespace = "")
        java.lang.String state,
        @WebParam(name = "street", targetNamespace = "")
        java.lang.String street,
        @WebParam(mode = WebParam.Mode.INOUT, name = "sys_id", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> sysId,
        @WebParam(name = "time_format", targetNamespace = "")
        java.lang.String timeFormat,
        @WebParam(name = "time_zone", targetNamespace = "")
        java.lang.String timeZone,
        @WebParam(name = "title", targetNamespace = "")
        java.lang.String title,
        @WebParam(name = "u_active_in_incident_tracking", targetNamespace = "")
        java.lang.Boolean uActiveInIncidentTracking,
        @WebParam(name = "u_active_in_partners_list", targetNamespace = "")
        java.lang.Boolean uActiveInPartnersList,
        @WebParam(name = "u_cube_number", targetNamespace = "")
        java.lang.String uCubeNumber,
        @WebParam(name = "u_director", targetNamespace = "")
        java.lang.String uDirector,
        @WebParam(name = "u_employee_type", targetNamespace = "")
        java.lang.String uEmployeeType,
        @WebParam(name = "u_group", targetNamespace = "")
        java.lang.String uGroup,
        @WebParam(name = "u_licensed_user", targetNamespace = "")
        java.lang.String uLicensedUser,
        @WebParam(name = "u_merchant_onboarding", targetNamespace = "")
        java.lang.String uMerchantOnboarding,
        @WebParam(name = "u_outage_notification", targetNamespace = "")
        java.lang.Boolean uOutageNotification,
        @WebParam(name = "u_page_at", targetNamespace = "")
        java.lang.String uPageAt,
        @WebParam(name = "u_partner_name", targetNamespace = "")
        java.lang.String uPartnerName,
        @WebParam(name = "u_preferred_name", targetNamespace = "")
        java.lang.String uPreferredName,
        @WebParam(name = "u_safeway_id", targetNamespace = "")
        java.lang.String uSafewayId,
        @WebParam(name = "u_type_of_user", targetNamespace = "")
        java.lang.String uTypeOfUser,
        @WebParam(name = "u_vp", targetNamespace = "")
        java.lang.String uVp,
        @WebParam(name = "user_name", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "user_password", targetNamespace = "")
        java.lang.String userPassword,
        @WebParam(name = "vip", targetNamespace = "")
        java.lang.Boolean vip,
        @WebParam(name = "zip", targetNamespace = "")
        java.lang.String zip
    );

    @WebResult(name = "count", targetNamespace = "")
    @RequestWrapper(localName = "deleteMultiple", targetNamespace = "http://www.service-now.com/sys_user", className = "com.blackhawk.servicenow.soap.client.DeleteMultiple")
    @WebMethod(action = "http://www.service-now.com/sys_user/deleteMultiple")
    @ResponseWrapper(localName = "deleteMultipleResponse", targetNamespace = "http://www.service-now.com/sys_user", className = "com.blackhawk.servicenow.soap.client.DeleteMultipleResponse")
    public java.lang.String deleteMultiple(
        @WebParam(name = "accumulated_roles", targetNamespace = "")
        java.lang.String accumulatedRoles,
        @WebParam(name = "active", targetNamespace = "")
        java.lang.Boolean active,
        @WebParam(name = "auditor", targetNamespace = "")
        java.lang.Boolean auditor,
        @WebParam(name = "building", targetNamespace = "")
        java.lang.String building,
        @WebParam(name = "calendar_integration", targetNamespace = "")
        java.lang.String calendarIntegration,
        @WebParam(name = "city", targetNamespace = "")
        java.lang.String city,
        @WebParam(name = "company", targetNamespace = "")
        java.lang.String company,
        @WebParam(name = "cost_center", targetNamespace = "")
        java.lang.String costCenter,
        @WebParam(name = "country", targetNamespace = "")
        java.lang.String country,
        @WebParam(name = "date_format", targetNamespace = "")
        java.lang.String dateFormat,
        @WebParam(name = "date_time_format", targetNamespace = "")
        java.lang.String dateTimeFormat,
        @WebParam(name = "default_perspective", targetNamespace = "")
        java.lang.String defaultPerspective,
        @WebParam(name = "department", targetNamespace = "")
        java.lang.String department,
        @WebParam(name = "edu_status", targetNamespace = "")
        java.lang.String eduStatus,
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email,
        @WebParam(name = "employee_number", targetNamespace = "")
        java.lang.String employeeNumber,
        @WebParam(name = "failed_attempts", targetNamespace = "")
        java.math.BigInteger failedAttempts,
        @WebParam(name = "first_name", targetNamespace = "")
        java.lang.String firstName,
        @WebParam(name = "gender", targetNamespace = "")
        java.lang.String gender,
        @WebParam(name = "home_phone", targetNamespace = "")
        java.lang.String homePhone,
        @WebParam(name = "introduction", targetNamespace = "")
        java.lang.String introduction,
        @WebParam(name = "last_login", targetNamespace = "")
        java.lang.String lastLogin,
        @WebParam(name = "last_login_device", targetNamespace = "")
        java.lang.String lastLoginDevice,
        @WebParam(name = "last_login_time", targetNamespace = "")
        java.lang.String lastLoginTime,
        @WebParam(name = "last_name", targetNamespace = "")
        java.lang.String lastName,
        @WebParam(name = "last_password", targetNamespace = "")
        java.lang.String lastPassword,
        @WebParam(name = "ldap_server", targetNamespace = "")
        java.lang.String ldapServer,
        @WebParam(name = "location", targetNamespace = "")
        java.lang.String location,
        @WebParam(name = "locked_out", targetNamespace = "")
        java.lang.Boolean lockedOut,
        @WebParam(name = "manager", targetNamespace = "")
        java.lang.String manager,
        @WebParam(name = "middle_name", targetNamespace = "")
        java.lang.String middleName,
        @WebParam(name = "mobile_phone", targetNamespace = "")
        java.lang.String mobilePhone,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "notification", targetNamespace = "")
        java.math.BigInteger notification,
        @WebParam(name = "password_needs_reset", targetNamespace = "")
        java.lang.Boolean passwordNeedsReset,
        @WebParam(name = "phone", targetNamespace = "")
        java.lang.String phone,
        @WebParam(name = "photo", targetNamespace = "")
        java.lang.String photo,
        @WebParam(name = "preferred_language", targetNamespace = "")
        java.lang.String preferredLanguage,
        @WebParam(name = "roles", targetNamespace = "")
        java.lang.String roles,
        @WebParam(name = "sales_account", targetNamespace = "")
        java.lang.String salesAccount,
        @WebParam(name = "sales_contact", targetNamespace = "")
        java.lang.String salesContact,
        @WebParam(name = "schedule", targetNamespace = "")
        java.lang.String schedule,
        @WebParam(name = "source", targetNamespace = "")
        java.lang.String source,
        @WebParam(name = "state", targetNamespace = "")
        java.lang.String state,
        @WebParam(name = "street", targetNamespace = "")
        java.lang.String street,
        @WebParam(name = "sys_class_name", targetNamespace = "")
        java.lang.String sysClassName,
        @WebParam(name = "sys_created_by", targetNamespace = "")
        java.lang.String sysCreatedBy,
        @WebParam(name = "sys_created_on", targetNamespace = "")
        java.lang.String sysCreatedOn,
        @WebParam(name = "sys_domain", targetNamespace = "")
        java.lang.String sysDomain,
        @WebParam(name = "sys_id", targetNamespace = "")
        java.lang.String sysId,
        @WebParam(name = "sys_mod_count", targetNamespace = "")
        java.math.BigInteger sysModCount,
        @WebParam(name = "sys_updated_by", targetNamespace = "")
        java.lang.String sysUpdatedBy,
        @WebParam(name = "sys_updated_on", targetNamespace = "")
        java.lang.String sysUpdatedOn,
        @WebParam(name = "time_format", targetNamespace = "")
        java.lang.String timeFormat,
        @WebParam(name = "time_zone", targetNamespace = "")
        java.lang.String timeZone,
        @WebParam(name = "title", targetNamespace = "")
        java.lang.String title,
        @WebParam(name = "u_active_in_incident_tracking", targetNamespace = "")
        java.lang.Boolean uActiveInIncidentTracking,
        @WebParam(name = "u_active_in_partners_list", targetNamespace = "")
        java.lang.Boolean uActiveInPartnersList,
        @WebParam(name = "u_cube_number", targetNamespace = "")
        java.lang.String uCubeNumber,
        @WebParam(name = "u_director", targetNamespace = "")
        java.lang.String uDirector,
        @WebParam(name = "u_employee_type", targetNamespace = "")
        java.lang.String uEmployeeType,
        @WebParam(name = "u_group", targetNamespace = "")
        java.lang.String uGroup,
        @WebParam(name = "u_licensed_user", targetNamespace = "")
        java.lang.String uLicensedUser,
        @WebParam(name = "u_merchant_onboarding", targetNamespace = "")
        java.lang.String uMerchantOnboarding,
        @WebParam(name = "u_outage_notification", targetNamespace = "")
        java.lang.Boolean uOutageNotification,
        @WebParam(name = "u_page_at", targetNamespace = "")
        java.lang.String uPageAt,
        @WebParam(name = "u_partner_name", targetNamespace = "")
        java.lang.String uPartnerName,
        @WebParam(name = "u_preferred_name", targetNamespace = "")
        java.lang.String uPreferredName,
        @WebParam(name = "u_safeway_id", targetNamespace = "")
        java.lang.String uSafewayId,
        @WebParam(name = "u_type_of_user", targetNamespace = "")
        java.lang.String uTypeOfUser,
        @WebParam(name = "u_vp", targetNamespace = "")
        java.lang.String uVp,
        @WebParam(name = "user_name", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "user_password", targetNamespace = "")
        java.lang.String userPassword,
        @WebParam(name = "vip", targetNamespace = "")
        java.lang.Boolean vip,
        @WebParam(name = "zip", targetNamespace = "")
        java.lang.String zip
    );

    @WebResult(name = "getRecordsResult", targetNamespace = "")
    @RequestWrapper(localName = "getRecords", targetNamespace = "http://www.service-now.com/sys_user", className = "com.blackhawk.servicenow.soap.client.GetRecords")
    @WebMethod(action = "http://www.service-now.com/sys_user/getRecords")
    @ResponseWrapper(localName = "getRecordsResponse", targetNamespace = "http://www.service-now.com/sys_user", className = "com.blackhawk.servicenow.soap.client.GetRecordsResponse")
    public java.util.List<com.blackhawk.servicenow.soap.client.GetRecordsResponse.GetRecordsResult> getRecords(
        @WebParam(name = "accumulated_roles", targetNamespace = "")
        java.lang.String accumulatedRoles,
        @WebParam(name = "active", targetNamespace = "")
        java.lang.Boolean active,
        @WebParam(name = "auditor", targetNamespace = "")
        java.lang.Boolean auditor,
        @WebParam(name = "building", targetNamespace = "")
        java.lang.String building,
        @WebParam(name = "calendar_integration", targetNamespace = "")
        java.lang.String calendarIntegration,
        @WebParam(name = "city", targetNamespace = "")
        java.lang.String city,
        @WebParam(name = "company", targetNamespace = "")
        java.lang.String company,
        @WebParam(name = "cost_center", targetNamespace = "")
        java.lang.String costCenter,
        @WebParam(name = "country", targetNamespace = "")
        java.lang.String country,
        @WebParam(name = "date_format", targetNamespace = "")
        java.lang.String dateFormat,
        @WebParam(name = "date_time_format", targetNamespace = "")
        java.lang.String dateTimeFormat,
        @WebParam(name = "default_perspective", targetNamespace = "")
        java.lang.String defaultPerspective,
        @WebParam(name = "department", targetNamespace = "")
        java.lang.String department,
        @WebParam(name = "edu_status", targetNamespace = "")
        java.lang.String eduStatus,
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email,
        @WebParam(name = "employee_number", targetNamespace = "")
        java.lang.String employeeNumber,
        @WebParam(name = "failed_attempts", targetNamespace = "")
        java.math.BigInteger failedAttempts,
        @WebParam(name = "first_name", targetNamespace = "")
        java.lang.String firstName,
        @WebParam(name = "gender", targetNamespace = "")
        java.lang.String gender,
        @WebParam(name = "home_phone", targetNamespace = "")
        java.lang.String homePhone,
        @WebParam(name = "introduction", targetNamespace = "")
        java.lang.String introduction,
        @WebParam(name = "last_login", targetNamespace = "")
        java.lang.String lastLogin,
        @WebParam(name = "last_login_device", targetNamespace = "")
        java.lang.String lastLoginDevice,
        @WebParam(name = "last_login_time", targetNamespace = "")
        java.lang.String lastLoginTime,
        @WebParam(name = "last_name", targetNamespace = "")
        java.lang.String lastName,
        @WebParam(name = "last_password", targetNamespace = "")
        java.lang.String lastPassword,
        @WebParam(name = "ldap_server", targetNamespace = "")
        java.lang.String ldapServer,
        @WebParam(name = "location", targetNamespace = "")
        java.lang.String location,
        @WebParam(name = "locked_out", targetNamespace = "")
        java.lang.Boolean lockedOut,
        @WebParam(name = "manager", targetNamespace = "")
        java.lang.String manager,
        @WebParam(name = "middle_name", targetNamespace = "")
        java.lang.String middleName,
        @WebParam(name = "mobile_phone", targetNamespace = "")
        java.lang.String mobilePhone,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "notification", targetNamespace = "")
        java.math.BigInteger notification,
        @WebParam(name = "password_needs_reset", targetNamespace = "")
        java.lang.Boolean passwordNeedsReset,
        @WebParam(name = "phone", targetNamespace = "")
        java.lang.String phone,
        @WebParam(name = "photo", targetNamespace = "")
        java.lang.String photo,
        @WebParam(name = "preferred_language", targetNamespace = "")
        java.lang.String preferredLanguage,
        @WebParam(name = "roles", targetNamespace = "")
        java.lang.String roles,
        @WebParam(name = "sales_account", targetNamespace = "")
        java.lang.String salesAccount,
        @WebParam(name = "sales_contact", targetNamespace = "")
        java.lang.String salesContact,
        @WebParam(name = "schedule", targetNamespace = "")
        java.lang.String schedule,
        @WebParam(name = "source", targetNamespace = "")
        java.lang.String source,
        @WebParam(name = "state", targetNamespace = "")
        java.lang.String state,
        @WebParam(name = "street", targetNamespace = "")
        java.lang.String street,
        @WebParam(name = "sys_class_name", targetNamespace = "")
        java.lang.String sysClassName,
        @WebParam(name = "sys_created_by", targetNamespace = "")
        java.lang.String sysCreatedBy,
        @WebParam(name = "sys_created_on", targetNamespace = "")
        java.lang.String sysCreatedOn,
        @WebParam(name = "sys_domain", targetNamespace = "")
        java.lang.String sysDomain,
        @WebParam(name = "sys_id", targetNamespace = "")
        java.lang.String sysId,
        @WebParam(name = "sys_mod_count", targetNamespace = "")
        java.math.BigInteger sysModCount,
        @WebParam(name = "sys_updated_by", targetNamespace = "")
        java.lang.String sysUpdatedBy,
        @WebParam(name = "sys_updated_on", targetNamespace = "")
        java.lang.String sysUpdatedOn,
        @WebParam(name = "time_format", targetNamespace = "")
        java.lang.String timeFormat,
        @WebParam(name = "time_zone", targetNamespace = "")
        java.lang.String timeZone,
        @WebParam(name = "title", targetNamespace = "")
        java.lang.String title,
        @WebParam(name = "u_active_in_incident_tracking", targetNamespace = "")
        java.lang.Boolean uActiveInIncidentTracking,
        @WebParam(name = "u_active_in_partners_list", targetNamespace = "")
        java.lang.Boolean uActiveInPartnersList,
        @WebParam(name = "u_cube_number", targetNamespace = "")
        java.lang.String uCubeNumber,
        @WebParam(name = "u_director", targetNamespace = "")
        java.lang.String uDirector,
        @WebParam(name = "u_employee_type", targetNamespace = "")
        java.lang.String uEmployeeType,
        @WebParam(name = "u_group", targetNamespace = "")
        java.lang.String uGroup,
        @WebParam(name = "u_licensed_user", targetNamespace = "")
        java.lang.String uLicensedUser,
        @WebParam(name = "u_merchant_onboarding", targetNamespace = "")
        java.lang.String uMerchantOnboarding,
        @WebParam(name = "u_outage_notification", targetNamespace = "")
        java.lang.Boolean uOutageNotification,
        @WebParam(name = "u_page_at", targetNamespace = "")
        java.lang.String uPageAt,
        @WebParam(name = "u_partner_name", targetNamespace = "")
        java.lang.String uPartnerName,
        @WebParam(name = "u_preferred_name", targetNamespace = "")
        java.lang.String uPreferredName,
        @WebParam(name = "u_safeway_id", targetNamespace = "")
        java.lang.String uSafewayId,
        @WebParam(name = "u_type_of_user", targetNamespace = "")
        java.lang.String uTypeOfUser,
        @WebParam(name = "u_vp", targetNamespace = "")
        java.lang.String uVp,
        @WebParam(name = "user_name", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "user_password", targetNamespace = "")
        java.lang.String userPassword,
        @WebParam(name = "vip", targetNamespace = "")
        java.lang.Boolean vip,
        @WebParam(name = "zip", targetNamespace = "")
        java.lang.String zip,
        @WebParam(name = "__use_view", targetNamespace = "")
        java.lang.String useView,
        @WebParam(name = "__encoded_query", targetNamespace = "")
        java.lang.String encodedQuery,
        @WebParam(name = "__limit", targetNamespace = "")
        java.lang.String limit,
        @WebParam(name = "__first_row", targetNamespace = "")
        java.lang.String firstRow,
        @WebParam(name = "__last_row", targetNamespace = "")
        java.lang.String lastRow,
        @WebParam(name = "__order_by", targetNamespace = "")
        java.lang.String orderBy,
        @WebParam(name = "__order_by_desc", targetNamespace = "")
        java.lang.String orderByDesc,
        @WebParam(name = "__exclude_columns", targetNamespace = "")
        java.lang.String excludeColumns
    );

    @RequestWrapper(localName = "getKeys", targetNamespace = "http://www.service-now.com/sys_user", className = "com.blackhawk.servicenow.soap.client.GetKeys")
    @WebMethod(action = "http://www.service-now.com/sys_user/getKeys")
    @ResponseWrapper(localName = "getKeysResponse", targetNamespace = "http://www.service-now.com/sys_user", className = "com.blackhawk.servicenow.soap.client.GetKeysResponse")
    public void getKeys(
        @WebParam(name = "accumulated_roles", targetNamespace = "")
        java.lang.String accumulatedRoles,
        @WebParam(name = "active", targetNamespace = "")
        java.lang.Boolean active,
        @WebParam(name = "auditor", targetNamespace = "")
        java.lang.Boolean auditor,
        @WebParam(name = "building", targetNamespace = "")
        java.lang.String building,
        @WebParam(name = "calendar_integration", targetNamespace = "")
        java.lang.String calendarIntegration,
        @WebParam(name = "city", targetNamespace = "")
        java.lang.String city,
        @WebParam(name = "company", targetNamespace = "")
        java.lang.String company,
        @WebParam(name = "cost_center", targetNamespace = "")
        java.lang.String costCenter,
        @WebParam(name = "country", targetNamespace = "")
        java.lang.String country,
        @WebParam(name = "date_format", targetNamespace = "")
        java.lang.String dateFormat,
        @WebParam(name = "date_time_format", targetNamespace = "")
        java.lang.String dateTimeFormat,
        @WebParam(name = "default_perspective", targetNamespace = "")
        java.lang.String defaultPerspective,
        @WebParam(name = "department", targetNamespace = "")
        java.lang.String department,
        @WebParam(name = "edu_status", targetNamespace = "")
        java.lang.String eduStatus,
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email,
        @WebParam(name = "employee_number", targetNamespace = "")
        java.lang.String employeeNumber,
        @WebParam(name = "failed_attempts", targetNamespace = "")
        java.math.BigInteger failedAttempts,
        @WebParam(name = "first_name", targetNamespace = "")
        java.lang.String firstName,
        @WebParam(name = "gender", targetNamespace = "")
        java.lang.String gender,
        @WebParam(name = "home_phone", targetNamespace = "")
        java.lang.String homePhone,
        @WebParam(name = "introduction", targetNamespace = "")
        java.lang.String introduction,
        @WebParam(name = "last_login", targetNamespace = "")
        java.lang.String lastLogin,
        @WebParam(name = "last_login_device", targetNamespace = "")
        java.lang.String lastLoginDevice,
        @WebParam(name = "last_login_time", targetNamespace = "")
        java.lang.String lastLoginTime,
        @WebParam(name = "last_name", targetNamespace = "")
        java.lang.String lastName,
        @WebParam(name = "last_password", targetNamespace = "")
        java.lang.String lastPassword,
        @WebParam(name = "ldap_server", targetNamespace = "")
        java.lang.String ldapServer,
        @WebParam(name = "location", targetNamespace = "")
        java.lang.String location,
        @WebParam(name = "locked_out", targetNamespace = "")
        java.lang.Boolean lockedOut,
        @WebParam(name = "manager", targetNamespace = "")
        java.lang.String manager,
        @WebParam(name = "middle_name", targetNamespace = "")
        java.lang.String middleName,
        @WebParam(name = "mobile_phone", targetNamespace = "")
        java.lang.String mobilePhone,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "notification", targetNamespace = "")
        java.math.BigInteger notification,
        @WebParam(name = "password_needs_reset", targetNamespace = "")
        java.lang.Boolean passwordNeedsReset,
        @WebParam(name = "phone", targetNamespace = "")
        java.lang.String phone,
        @WebParam(name = "photo", targetNamespace = "")
        java.lang.String photo,
        @WebParam(name = "preferred_language", targetNamespace = "")
        java.lang.String preferredLanguage,
        @WebParam(name = "roles", targetNamespace = "")
        java.lang.String roles,
        @WebParam(name = "sales_account", targetNamespace = "")
        java.lang.String salesAccount,
        @WebParam(name = "sales_contact", targetNamespace = "")
        java.lang.String salesContact,
        @WebParam(name = "schedule", targetNamespace = "")
        java.lang.String schedule,
        @WebParam(name = "source", targetNamespace = "")
        java.lang.String source,
        @WebParam(name = "state", targetNamespace = "")
        java.lang.String state,
        @WebParam(name = "street", targetNamespace = "")
        java.lang.String street,
        @WebParam(name = "sys_class_name", targetNamespace = "")
        java.lang.String sysClassName,
        @WebParam(name = "sys_created_by", targetNamespace = "")
        java.lang.String sysCreatedBy,
        @WebParam(name = "sys_created_on", targetNamespace = "")
        java.lang.String sysCreatedOn,
        @WebParam(name = "sys_domain", targetNamespace = "")
        java.lang.String sysDomain,
        @WebParam(name = "sys_mod_count", targetNamespace = "")
        java.math.BigInteger sysModCount,
        @WebParam(name = "sys_updated_by", targetNamespace = "")
        java.lang.String sysUpdatedBy,
        @WebParam(name = "sys_updated_on", targetNamespace = "")
        java.lang.String sysUpdatedOn,
        @WebParam(name = "time_format", targetNamespace = "")
        java.lang.String timeFormat,
        @WebParam(name = "time_zone", targetNamespace = "")
        java.lang.String timeZone,
        @WebParam(name = "title", targetNamespace = "")
        java.lang.String title,
        @WebParam(name = "u_active_in_incident_tracking", targetNamespace = "")
        java.lang.Boolean uActiveInIncidentTracking,
        @WebParam(name = "u_active_in_partners_list", targetNamespace = "")
        java.lang.Boolean uActiveInPartnersList,
        @WebParam(name = "u_cube_number", targetNamespace = "")
        java.lang.String uCubeNumber,
        @WebParam(name = "u_director", targetNamespace = "")
        java.lang.String uDirector,
        @WebParam(name = "u_employee_type", targetNamespace = "")
        java.lang.String uEmployeeType,
        @WebParam(name = "u_group", targetNamespace = "")
        java.lang.String uGroup,
        @WebParam(name = "u_licensed_user", targetNamespace = "")
        java.lang.String uLicensedUser,
        @WebParam(name = "u_merchant_onboarding", targetNamespace = "")
        java.lang.String uMerchantOnboarding,
        @WebParam(name = "u_outage_notification", targetNamespace = "")
        java.lang.Boolean uOutageNotification,
        @WebParam(name = "u_page_at", targetNamespace = "")
        java.lang.String uPageAt,
        @WebParam(name = "u_partner_name", targetNamespace = "")
        java.lang.String uPartnerName,
        @WebParam(name = "u_preferred_name", targetNamespace = "")
        java.lang.String uPreferredName,
        @WebParam(name = "u_safeway_id", targetNamespace = "")
        java.lang.String uSafewayId,
        @WebParam(name = "u_type_of_user", targetNamespace = "")
        java.lang.String uTypeOfUser,
        @WebParam(name = "u_vp", targetNamespace = "")
        java.lang.String uVp,
        @WebParam(name = "user_name", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "user_password", targetNamespace = "")
        java.lang.String userPassword,
        @WebParam(name = "vip", targetNamespace = "")
        java.lang.Boolean vip,
        @WebParam(name = "zip", targetNamespace = "")
        java.lang.String zip,
        @WebParam(name = "__use_view", targetNamespace = "")
        java.lang.String useView,
        @WebParam(name = "__encoded_query", targetNamespace = "")
        java.lang.String encodedQuery,
        @WebParam(name = "__limit", targetNamespace = "")
        java.lang.String limit,
        @WebParam(name = "__first_row", targetNamespace = "")
        java.lang.String firstRow,
        @WebParam(name = "__last_row", targetNamespace = "")
        java.lang.String lastRow,
        @WebParam(mode = WebParam.Mode.OUT, name = "sys_id", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<java.lang.String>> sysId,
        @WebParam(mode = WebParam.Mode.OUT, name = "count", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> count
    );

    @RequestWrapper(localName = "get", targetNamespace = "http://www.service-now.com/sys_user", className = "com.blackhawk.servicenow.soap.client.Get", partName = "sys_user")
    @WebMethod(operationName="get", action = "http://www.service-now.com/sys_user/get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://www.service-now.com/sys_user", className = "com.blackhawk.servicenow.soap.client.GetResponse", partName = "sys_user")
    public void get(
        @WebParam(mode = WebParam.Mode.INOUT, name = "sys_id", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> sysId,
        @WebParam(name = "__use_view", targetNamespace = "")
        java.lang.String useView,
        @WebParam(mode = WebParam.Mode.OUT, name = "accumulated_roles", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> accumulatedRoles,
        @WebParam(mode = WebParam.Mode.OUT, name = "active", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> active,
        @WebParam(mode = WebParam.Mode.OUT, name = "auditor", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> auditor,
        @WebParam(mode = WebParam.Mode.OUT, name = "building", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> building,
        @WebParam(mode = WebParam.Mode.OUT, name = "calendar_integration", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> calendarIntegration,
        @WebParam(mode = WebParam.Mode.OUT, name = "city", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> city,
        @WebParam(mode = WebParam.Mode.OUT, name = "company", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> company,
        @WebParam(mode = WebParam.Mode.OUT, name = "cost_center", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> costCenter,
        @WebParam(mode = WebParam.Mode.OUT, name = "country", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> country,
        @WebParam(mode = WebParam.Mode.OUT, name = "date_format", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> dateFormat,
        @WebParam(mode = WebParam.Mode.OUT, name = "date_time_format", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> dateTimeFormat,
        @WebParam(mode = WebParam.Mode.OUT, name = "default_perspective", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> defaultPerspective,
        @WebParam(mode = WebParam.Mode.OUT, name = "department", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> department,
        @WebParam(mode = WebParam.Mode.OUT, name = "edu_status", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eduStatus,
        @WebParam(mode = WebParam.Mode.OUT, name = "email", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> email,
        @WebParam(mode = WebParam.Mode.OUT, name = "employee_number", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> employeeNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "failed_attempts", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigInteger> failedAttempts,
        @WebParam(mode = WebParam.Mode.OUT, name = "first_name", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> firstName,
        @WebParam(mode = WebParam.Mode.OUT, name = "gender", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> gender,
        @WebParam(mode = WebParam.Mode.OUT, name = "home_phone", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> homePhone,
        @WebParam(mode = WebParam.Mode.OUT, name = "introduction", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> introduction,
        @WebParam(mode = WebParam.Mode.OUT, name = "last_login", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> lastLogin,
        @WebParam(mode = WebParam.Mode.OUT, name = "last_login_device", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> lastLoginDevice,
        @WebParam(mode = WebParam.Mode.OUT, name = "last_login_time", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> lastLoginTime,
        @WebParam(mode = WebParam.Mode.OUT, name = "last_name", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> lastName,
        @WebParam(mode = WebParam.Mode.OUT, name = "last_password", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> lastPassword,
        @WebParam(mode = WebParam.Mode.OUT, name = "ldap_server", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> ldapServer,
        @WebParam(mode = WebParam.Mode.OUT, name = "location", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> location,
        @WebParam(mode = WebParam.Mode.OUT, name = "locked_out", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> lockedOut,
        @WebParam(mode = WebParam.Mode.OUT, name = "manager", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> manager,
        @WebParam(mode = WebParam.Mode.OUT, name = "middle_name", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> middleName,
        @WebParam(mode = WebParam.Mode.OUT, name = "mobile_phone", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> mobilePhone,
        @WebParam(mode = WebParam.Mode.OUT, name = "name", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> name,
        @WebParam(mode = WebParam.Mode.OUT, name = "notification", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigInteger> notification,
        @WebParam(mode = WebParam.Mode.OUT, name = "password_needs_reset", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> passwordNeedsReset,
        @WebParam(mode = WebParam.Mode.OUT, name = "phone", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> phone,
        @WebParam(mode = WebParam.Mode.OUT, name = "photo", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> photo,
        @WebParam(mode = WebParam.Mode.OUT, name = "preferred_language", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> preferredLanguage,
        @WebParam(mode = WebParam.Mode.OUT, name = "roles", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> roles,
        @WebParam(mode = WebParam.Mode.OUT, name = "sales_account", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> salesAccount,
        @WebParam(mode = WebParam.Mode.OUT, name = "sales_contact", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> salesContact,
        @WebParam(mode = WebParam.Mode.OUT, name = "schedule", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> schedule,
        @WebParam(mode = WebParam.Mode.OUT, name = "source", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> source,
        @WebParam(mode = WebParam.Mode.OUT, name = "state", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> state,
        @WebParam(mode = WebParam.Mode.OUT, name = "street", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> street,
        @WebParam(mode = WebParam.Mode.OUT, name = "sys_class_name", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> sysClassName,
        @WebParam(mode = WebParam.Mode.OUT, name = "sys_created_by", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> sysCreatedBy,
        @WebParam(mode = WebParam.Mode.OUT, name = "sys_created_on", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> sysCreatedOn,
        @WebParam(mode = WebParam.Mode.OUT, name = "sys_domain", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> sysDomain,
        @WebParam(mode = WebParam.Mode.OUT, name = "sys_mod_count", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigInteger> sysModCount,
        @WebParam(mode = WebParam.Mode.OUT, name = "sys_updated_by", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> sysUpdatedBy,
        @WebParam(mode = WebParam.Mode.OUT, name = "sys_updated_on", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> sysUpdatedOn,
        @WebParam(mode = WebParam.Mode.OUT, name = "time_format", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> timeFormat,
        @WebParam(mode = WebParam.Mode.OUT, name = "time_zone", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> timeZone,
        @WebParam(mode = WebParam.Mode.OUT, name = "title", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> title,
        @WebParam(mode = WebParam.Mode.OUT, name = "u_active_in_incident_tracking", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> uActiveInIncidentTracking,
        @WebParam(mode = WebParam.Mode.OUT, name = "u_active_in_partners_list", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> uActiveInPartnersList,
        @WebParam(mode = WebParam.Mode.OUT, name = "u_cube_number", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> uCubeNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "u_director", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> uDirector,
        @WebParam(mode = WebParam.Mode.OUT, name = "u_employee_type", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> uEmployeeType,
        @WebParam(mode = WebParam.Mode.OUT, name = "u_group", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> uGroup,
        @WebParam(mode = WebParam.Mode.OUT, name = "u_licensed_user", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> uLicensedUser,
        @WebParam(mode = WebParam.Mode.OUT, name = "u_merchant_onboarding", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> uMerchantOnboarding,
        @WebParam(mode = WebParam.Mode.OUT, name = "u_outage_notification", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> uOutageNotification,
        @WebParam(mode = WebParam.Mode.OUT, name = "u_page_at", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> uPageAt,
        @WebParam(mode = WebParam.Mode.OUT, name = "u_partner_name", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> uPartnerName,
        @WebParam(mode = WebParam.Mode.OUT, name = "u_preferred_name", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> uPreferredName,
        @WebParam(mode = WebParam.Mode.OUT, name = "u_safeway_id", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> uSafewayId,
        @WebParam(mode = WebParam.Mode.OUT, name = "u_type_of_user", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> uTypeOfUser,
        @WebParam(mode = WebParam.Mode.OUT, name = "u_vp", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> uVp,
        @WebParam(mode = WebParam.Mode.OUT, name = "user_name", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> userName,
        @WebParam(mode = WebParam.Mode.OUT, name = "user_password", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> userPassword,
        @WebParam(mode = WebParam.Mode.OUT, name = "vip", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> vip,
        @WebParam(mode = WebParam.Mode.OUT, name = "zip", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> zip
    );
}
